name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v4
      
    - name: Login to docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./payoneer
        file: ./payoneer/Dockerfile
        push: true
        tags: markus1258/payoneer:latest, markus1258/payoneer:${{ github.sha }}
